# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/mitalibora01/Regression-Model-to-Predict-Cement-Compressive-Strength/blob/main/Project.ipynb
"""

import pandas as pd
import seaborn as sns
import os
import numpy as np
import matplotlib.pyplot as plt

cement = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Concrete%20Compressive%20Strength.csv')

cement

cement.info()

cement.describe()

cement.isnull()

cement.isnull().sum()

cement.count()

cement.nunique()

sns.pairplot(cement)

cement.columns

updated_col_names = ['Cement','Blast Furnace Slag','Fly Ash','Water','Superplasticizer','Coarse Aggregate','Fine Aggregate','Age','Compressive Strength']

cement.columns = updated_col_names

updated_col_names

cement.columns

y=cement['Compressive Strength']

cols = cement.columns.drop('Compressive Strength')

X = cement[cols]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=2529)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

from sklearn.linear_model import LinearRegression 
model=LinearRegression()

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

mean_absolute_error(y_test,y_pred)

mean_absolute_percentage_error(y_test,y_pred)

mean_squared_error(y_test,y_pred)

model.predict([[540,0,0,162,2.5,1040,676,28]])

cement.columns

X_new = [[['Cement',540],['Blast Furnace Slag',0],['Fly Ash',0],['Water',162],['Superplasticizer',2.5],['Coarse Aggregate',1040],['Fine Aggregate',676],['Age',28]]]
X_new = np.array([540,0,0,162,2.5,1040,676,28]).reshape(-1,8)
X_new.shape

model.predict(X_new)